#端口号
application:
  name: maxkey-gateway-server
  formatted-version: v3.5.2 GA
server:
  port: 9000
spring:
  application:
    name: maxkey-gateway-server
  cloud:
    gateway:
      routes:
#nacos健康检查端口8080
        - id: maxkeys_route
          uri: lb://sign
          filters:
            - PrefixPath=/
          predicates:
            - Path=/sign/**
        - id: maxkey_mgts_route
          uri: lb://maxkey-mgt-api
          filters:
            - PrefixPath=/
          predicates:
            - Path=/maxkey-mgt-api/**
#      default-filters:
#       - name: Hystrix
#          args:
#            name: default
#            fallbackUri: 'forward:/defaultFallback'
        
  main:
    web-application-type: reactive
#spring.main.web-application-type=reactive
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            #1分钟服务无响应则直接熔断
            timeoutInMilliseconds: 60000
            